name: Deploy React Frontend

# Запуск при пуше в master или вручную
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Копируем файлы на сервер
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: ./*
          target: $HOME/${{ env.REPO_NAME }}/

      # 3. Деплой React через Docker
      - name: Deploy Frontend
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd $HOME/${{ env.REPO_NAME }}/

            # Билдим и пушим образ (если используешь GHCR)
            docker build -t rail-front -f ./.deploy/prod/Dockerfile .
            
            # Поднимаем контейнер через Docker Compose
            docker compose up -d --force-recreate
            
            # Очистка старых образов
            docker image prune -af
